USE `movie_viewing_service_db` ;

CREATE TABLE `user` ( `id` INTEGER NOT NULL AUTO_INCREMENT , `login` VARCHAR ( 32 ) NOT NULL UNIQUE , `password` VARCHAR ( 255 ) NOT NULL , `role` TINYINT NOT NULL CHECK ( `role` IN ( 0 , 1 , 2 ) ) , PRIMARY KEY ( `id` ) ) DEFAULT CHARACTER SET utf8;

CREATE TABLE `country` ( `id` INTEGER NOT NULL AUTO_INCREMENT , `name` VARCHAR ( 255 ) NOT NULL , PRIMARY KEY ( `id` ) ) DEFAULT CHARACTER SET utf8;

CREATE TABLE `category` ( `id` INTEGER NOT NULL AUTO_INCREMENT , `name` VARCHAR ( 255 ) NOT NULL , PRIMARY KEY ( `id` ) ) DEFAULT CHARACTER SET utf8;

CREATE TABLE `user_info` ( `user_id` INTEGER NOT NULL UNIQUE , `country_id` INTEGER , `email` VARCHAR ( 255 ) UNIQUE , `sex` CHAR ( 1 ) CHECK ( `sex` IN ( 'm' ,  'w' ) ) , `birth_date` DATE , FOREIGN KEY ( `user_id` ) REFERENCES `user` ( `id` ) ON
UPDATE CASCADE ON
DELETE
CASCADE,
FOREIGN KEY ( `country_id` ) REFERENCES `country` ( `id` ) ON
UPDATE CASCADE ON
DELETE CASCADE ) DEFAULT CHARACTER SET utf8;

CREATE TABLE `film` ( `id` INTEGER NOT NULL AUTO_INCREMENT , `name` VARCHAR ( 255 ) NOT NULL , `release_date` DATE NOT NULL , `image_path` VARCHAR ( 255 ) , `description` TEXT , `country_id` INTEGER , `category_id` INTEGER , PRIMARY KEY ( `id` ) , FOREIGN KEY ( `country_id` ) REFERENCES `country` ( `id` ) ON
UPDATE CASCADE ON
DELETE
RESTRICT,
FOREIGN KEY ( `category_id` ) REFERENCES `category` ( `id` ) ON
UPDATE CASCADE ON
DELETE RESTRICT ) DEFAULT CHARACTER SET utf8;

CREATE TABLE `see_later` ( `id` INTEGER NOT NULL AUTO_INCREMENT , `user_id` INTEGER NOT NULL , `film_id` INTEGER NOT NULL , PRIMARY KEY ( `id` ) , FOREIGN KEY ( `user_id` ) REFERENCES `user` ( `id` ) ON
UPDATE CASCADE ON
DELETE
CASCADE,
FOREIGN KEY ( `film_id` ) REFERENCES `film` ( `id` ) ON
UPDATE CASCADE ON
DELETE CASCADE ) DEFAULT CHARACTER SET utf8;

CREATE TABLE `viewed_before` ( `id` INTEGER NOT NULL AUTO_INCREMENT , `user_id` INTEGER NOT NULL , `film_id` INTEGER NOT NULL , PRIMARY KEY ( `id` ) , FOREIGN KEY ( `user_id` ) REFERENCES `user` ( `id` ) ON
UPDATE CASCADE ON
DELETE
CASCADE,
FOREIGN KEY ( `film_id` ) REFERENCES `film` ( `id` ) ON
UPDATE CASCADE ON
DELETE CASCADE ) DEFAULT CHARACTER SET utf8;
